name: Nottus Universe-City
favicon: null
layout_spectrum: 0.7942430339753628
typography_spectrum: 0.3106079613789916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060f16'
    - '#ffffff'
    - '#11447b'
    - '#388ad6'
    - '#82b7f2'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
