name: Nottus Universe-City
favicon: null
layout_spectrum: 0.7942430339753628
typography_spectrum: 0.3106079613789916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.47913194284774363
  lightness: 0.7268084727693349
  saturation: 0.45553803350776434
  rhythmicContrast: 0.5120327293407172
purpose: []
